name: CD ACA

on:
  workflow_dispatch:
    inputs:  
        IMAGE_TAG:
          description: "Image tag to be deployed"
          required: true
        FIRST_DEPLOY:
          description: "Is this the first deployment?"
          required: true
          default: "false"

jobs:
  deploy-container-apps:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Using https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect
    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Enable debug logs
      run: echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV

    - name: Create resource group if it does not exist
      run: |
        az group create --name ${{ secrets.AZURE_RESOURCE_GROUP }} --location eastus

    
    - name: Create Azure Container App solution
      run: |
        az deployment group create \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --template-file infra/main.bicep \
          --parameters useNewContainerAppModule=${{ github.event.inputs.FIRST_DEPLOY }}  weatherApiKey=${{ secrets.WEATHER_API_KEY }} acrName=${{ secrets.ACR_NAME }} containerImage=${{ secrets.ACR_NAME }}.azurecr.io/net8-app:${{ github.event.inputs.IMAGE_TAG }}

    